# -*- coding: utf-8 -*-
"""Final Project Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYR-Ne6lD8w0gQHCuKymI98-KNRI7gg2
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import glob

def evaluate_attack_logic(slot_name, atk_mass, paw_mass):
    if slot_name == "Enemy_0":
        if (atk_mass > 0.22) or (atk_mass < 0.10): return True
        elif (0.14 < atk_mass < 0.21) and (paw_mass < 0.40): return True
        elif (0.20 < atk_mass < 0.22) and (paw_mass > 0.25): return True
        else: return False

    elif slot_name == "Enemy_1":
        if (atk_mass > 0.285) or (atk_mass < 0.205): return True
        elif (0.27 < atk_mass < 0.285) and (paw_mass < 0.27): return True
        elif (0.25 < atk_mass < 0.27) and (paw_mass < 0.30): return True
        else: return False

    elif slot_name == "Enemy_2":
        if (atk_mass > 0.32) or (atk_mass < 0.21) or (paw_mass < 0.12): return True
        elif (0.265 < atk_mass < 0.285) and (0.28 < paw_mass < 0.3): return True
        elif (0.3 < atk_mass < 0.32) and (paw_mass < 0.15): return True
        else: return False

    elif slot_name == "Enemy_3":
        if (atk_mass > 0.375) or (atk_mass < 0.305): return True
        elif (atk_mass < 0.375) and (paw_mass < 0.3): return True
        elif (0.34 < atk_mass < 0.37) and (0.345 < paw_mass < 0.4): return True
        else: return False

    elif slot_name == "Player_0":
        if paw_mass < 0.22 or paw_mass > 0.3 or atk_mass > 0.28: return True
        else: return False

    elif slot_name == "Player_1":
        if atk_mass > 0.22 or atk_mass < 0.12: return True
        else: return False

    elif slot_name == "Player_2":
        if atk_mass > 0.20 or atk_mass < 0.08: return True
        elif atk_mass < 0.15 and paw_mass < 0.3: return True
        else: return False

    elif slot_name == "Player_3":
        if (paw_mass < 0.38) or (atk_mass > 0.25 and paw_mass < 0.4): return True
        else: return False

    return False

def get_ink_mass(corner_roi, full_card_roi):
    card_gray = cv2.cvtColor(full_card_roi, cv2.COLOR_BGR2GRAY)
    card_blurred = cv2.GaussianBlur(card_gray, (3, 3), 0)
    paper_val = np.percentile(card_blurred, 95)
    ink_val = np.percentile(card_blurred, 5)
    stat_ink_threshold = ink_val + ((paper_val - ink_val) * 0.25)
    corner_gray = cv2.cvtColor(corner_roi, cv2.COLOR_BGR2GRAY)
    corner_blurred = cv2.GaussianBlur(corner_gray, (3, 3), 0)
    _, mask = cv2.threshold(corner_blurred, stat_ink_threshold, 255, cv2.THRESH_BINARY_INV)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((3, 3), np.uint8))
    total_pixels = corner_roi.shape[0] * corner_roi.shape[1]
    return cv2.countNonZero(mask) / total_pixels

def get_local_ink_mass(corner_roi):
    corner_gray = cv2.cvtColor(corner_roi, cv2.COLOR_BGR2GRAY)
    corner_blurred = cv2.GaussianBlur(corner_gray, (3, 3), 0)
    paper_val = np.percentile(corner_blurred, 95)
    ink_val = np.percentile(corner_blurred, 5)
    if paper_val - ink_val < 10:
        return 0.0
    stat_ink_threshold = ink_val + ((paper_val - ink_val) * 0.35)
    _, mask = cv2.threshold(corner_blurred, stat_ink_threshold, 255, cv2.THRESH_BINARY_INV)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((3, 3), np.uint8))
    total_pixels = corner_roi.shape[0] * corner_roi.shape[1]
    return cv2.countNonZero(mask) / total_pixels

def evaluate_health_logic(slot_name, hp_mass, attack_found):
    if slot_name in ["Enemy_0", "Enemy_1", "Enemy_2", "Enemy_3"]:
        if (not attack_found) and ((0.120 < hp_mass < 0.123) or (0.207 < hp_mass < 0.303)):
            return False
        if hp_mass > 0.020:
            return True
        return False
    elif slot_name in ["Player_0", "Player_1", "Player_2", "Player_3"]:
        if hp_mass > 0.010:
            return True
        return False

    return False

def is_card_present(roi):
    h, w = roi.shape[:2]
    gray_roi = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray_roi, (5, 5), 0)
    edges = cv2.Canny(blurred, 40, 120)
    density = cv2.countNonZero(edges) / (w * h)
    if density > 0.035:
        return True, "Edge Density"
    center_gray = gray_roi[int(h*0.3):int(h*0.7), int(w*0.3):int(w*0.7)]
    mean_brightness = np.mean(center_gray)
    contrast_std = np.std(center_gray)
    if 77 > mean_brightness > 70 or 67 > mean_brightness > 65 or 55 > mean_brightness > 50:
        if 14.0 < contrast_std < 16.0 or 21.5 < contrast_std < 24.5:
          return True, "Table Test"
    return False, ""


player_y, player_w, player_h = 810, 440, 665
enemy_y, enemy_w, enemy_h = 175, 410, 580

slots = {
    "Enemy_0": [470, enemy_y, enemy_w, enemy_h],
    "Enemy_1": [910, enemy_y, enemy_w, enemy_h],
    "Enemy_2": [1350, enemy_y, enemy_w, enemy_h],
    "Enemy_3": [1790, enemy_y, enemy_w, enemy_h],
    "Player_0": [420, player_y, player_w, player_h],
    "Player_1": [890, player_y, player_w, player_h],
    "Player_2": [1370, player_y, player_w, player_h],
    "Player_3": [1840, player_y, player_w, player_h],
}


def squash_to_32(blob):
    h, w = blob.shape[:2]
    side = max(w, h)
    square = np.zeros((side, side), dtype=np.uint8)
    x_off = (side - w) // 2
    y_off = (side - h) // 2
    square[y_off:y_off+h, x_off:x_off+w] = blob
    return cv2.resize(square, (32, 32))

def create_32x32_signature(img_path):
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is None: return None
    blur = cv2.GaussianBlur(img, (5, 5), 0)
    p5 = np.percentile(blur, 5)
    p50 = np.median(blur)
    p95 = np.percentile(blur, 95)
    is_glowing = (p95 - p50) > (p50 - p5)
    if is_glowing:
        thresh_val = p50 + ((p95 - p50) * 0.40)
        _, thresh = cv2.threshold(blur, thresh_val, 255, cv2.THRESH_BINARY)
    else:
        thresh_val = p5 + ((p50 - p5) * 0.40)
        _, thresh = cv2.threshold(blur, thresh_val, 255, cv2.THRESH_BINARY_INV)
    clean = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, np.ones((5,5), np.uint8))
    coords = cv2.findNonZero(clean)
    if coords is not None:
        x, y, w, h = cv2.boundingRect(coords)
        blob = clean[y:y+h, x:x+w]
        return squash_to_32(blob)
    return None

image_paths = glob.glob("*.png")
for image_path in image_paths:

    original_img = cv2.imread(image_path)
    if original_img is None: continue

    output_img = original_img.copy()
    extracted_stats = {}

    for slot_name, coords in slots.items():
        x, y, w, h = coords
        roi = original_img[y:y+h, x:x+w]

        card_exists, detection_method = is_card_present(roi)

        if card_exists:
            cv2.rectangle(output_img, (x, y), (x + w, y + h), (0, 255, 0), 6)
            cv2.putText(output_img, f"[{detection_method}]", (x + 5, y + 25), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

            atk_y_start, atk_y_end = int(h * 0.65), int(h * 0.85)
            paw_y_start, paw_y_end = int(h * 0.85), int(h * 0.95)
            atk_x_start, atk_x_end = 0, int(w * 0.28)

            hp_y_start, hp_y_end = int(h * 0.70), int(h * 0.95)
            hp_x_start, hp_x_end = int(w * 0.68), w

            atk_roi = roi[atk_y_start:atk_y_end, atk_x_start:atk_x_end]
            paw_roi = roi[paw_y_start:paw_y_end, atk_x_start:atk_x_end]
            hp_roi = roi[hp_y_start:hp_y_end, hp_x_start:hp_x_end]

            atk_mass = get_ink_mass(atk_roi, roi)
            paw_mass = get_ink_mass(paw_roi, roi)
            hp_mass = get_local_ink_mass(hp_roi)


            attack_found = evaluate_attack_logic(slot_name, atk_mass, paw_mass)

            if attack_found:
                extracted_stats[f"{slot_name}_Attack"] = "Found"
                cv2.rectangle(output_img, (x + atk_x_start, y + atk_y_start), (x + atk_x_end, y + atk_y_end), (0, 0, 255), 4)
                cv2.putText(output_img, f"A:{atk_mass:.3f}", (x + 5, y + atk_y_start - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)

            health_found = evaluate_health_logic(slot_name, hp_mass, attack_found)

            if health_found:
                  extracted_stats[f"{slot_name}_Health"] = "Found"
                  cv2.rectangle(output_img, (x + hp_x_start, y + hp_y_start), (x + hp_x_end, y + hp_y_end), (255, 0, 0), 4)
                  cv2.putText(output_img, f"H:{hp_mass:.3f}", (x + int(w * 0.7) + 5, y + hp_y_start - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

            sigil_y_start, sigil_y_end = int(h * 0.70), int(h * 0.95)
            sigil_x_start, sigil_x_end = int(w * 0.15), int(w * 0.85)

            sigil_roi = roi[sigil_y_start:sigil_y_end, sigil_x_start:sigil_x_end]
            sigil_gray = cv2.cvtColor(sigil_roi, cv2.COLOR_BGR2GRAY)
            sigil_blur = cv2.GaussianBlur(sigil_gray, (3, 3), 0)

            paper_val = np.median(sigil_blur)
            dark_ink_val = np.percentile(sigil_blur, 5)
            bright_ink_val = np.percentile(sigil_blur, 95)

            raw_contours = []

            morph_kernel = np.ones((21, 21), np.uint8)

            if paper_val - dark_ink_val > 15:
                thresh_val = dark_ink_val + ((paper_val - dark_ink_val) * 0.20)
                _, clean_dark = cv2.threshold(sigil_blur, thresh_val, 255, cv2.THRESH_BINARY_INV)
                clean_dark = cv2.morphologyEx(clean_dark, cv2.MORPH_CLOSE, np.ones((5,5), np.uint8))
                box_mask_dark = cv2.dilate(clean_dark, morph_kernel)
                contours, _ = cv2.findContours(box_mask_dark, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
                raw_contours.extend(contours)

            if bright_ink_val - paper_val > 45:
                thresh_val = bright_ink_val - ((bright_ink_val - paper_val) * 0.20)
                _, clean_bright = cv2.threshold(sigil_blur, thresh_val, 255, cv2.THRESH_BINARY)
                clean_bright = cv2.morphologyEx(clean_bright, cv2.MORPH_CLOSE, np.ones((5,5), np.uint8))
                box_mask_bright = cv2.dilate(clean_bright, morph_kernel)
                contours, _ = cv2.findContours(box_mask_bright, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
                raw_contours.extend(contours)

            detected_centers = []
            sigil_count = 0

            for cnt in raw_contours:
                sx, sy, sw, sh = cv2.boundingRect(cnt)
                bbox_area = sw * sh

                if bbox_area < 1500: continue

                cx = sx + (sw // 2)
                cy = sy + (sh // 2)
                abs_cx = sigil_x_start + cx

                if abs_cx < int(w * 0.30) or abs_cx > int(w * 0.70):
                    continue

                is_duplicate = False
                for (ex, ey) in detected_centers:
                    if abs(cx - ex) < 80 and abs(cy - ey) < 80:
                        is_duplicate = True
                        break

                if is_duplicate: continue
                detected_centers.append((cx, cy))
                sigil_count += 1
                MAX_AREA = 40000

                if bbox_area <= MAX_AREA:
                    is_valid = True
                    box_size = 130
                    label = f"Sigil A:{bbox_area}"
                    color = (0, 255, 255)
                else:
                    is_valid = False
                    box_size = max(sw, sh) + 15
                    label = f"Ign A:{bbox_area}"
                    color = (255, 0, 255)

                half_size = box_size // 2
                top_left_x = x + sigil_x_start + cx - half_size
                top_left_y = y + sigil_y_start + cy - half_size
                bot_right_x = top_left_x + box_size
                bot_right_y = top_left_y + box_size
                thickness = 4 if is_valid else 0
                font_scale = 0.5 if is_valid else 0
                cv2.rectangle(output_img, (top_left_x, top_left_y), (bot_right_x, bot_right_y), color, thickness)
                cv2.putText(output_img, label, (top_left_x, top_left_y - 8), cv2.FONT_HERSHEY_SIMPLEX, font_scale, color, 2)
                if is_valid:
                    extracted_stats[f"{slot_name}_Sigil_Found_{sigil_count}"] = "Found"
        else:
            cv2.rectangle(output_img, (x, y), (x + w, y + h), (0, 0, 255), 3)
            cv2.putText(output_img, f"[{detection_method}]", (x + 5, y + 25), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)

    plt.figure(figsize=(16, 10))
    plt.imshow(cv2.cvtColor(output_img, cv2.COLOR_BGR2RGB))
    plt.axis('off')
    plt.title(f"{image_path}")
    plt.show()